sudo: required

dist: trusty

language: node_js

node_js: '10'

install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH ;

before_script:
  - cd io.opencaesar.oml.theia

script:
  - chmod a+x /home/travis/build/opencaesar/oml-theia/io.opencaesar.oml.theia/node_modules/vscode-ripgrep/bin/rg
  - yarn

env:
  global:
  - secure: zs4oYaOFJZbU1VVNKplJwOsewU3sNujt9cYUzD1SpMrjqYQHEbrBXpX+WFET0nhWnCvb45i/Ui/vsUkAEPRFtn09ruF4mR+5pi5B5vt35fDqmK+vbXnpSuFGnHBQHV9TnvcLqaFkS+dlMV68DZXboxHt/X2Y8wFxVwvUKSQ0YBEdyiYWsQK3FM99c0bPzb26lG8Ps/iqOrOp/mfzd6YsN0oInqAAgTICLYIzq5w9MfjxGI9QEc6yxkwm6Mcgfq+BUut52ylDb+f5Sn12sr+m7BGZZ3J/NPL35KhR31KHuCMkr4fyxtL0mnfpstKRZYqYkBOj3rJefUZ1MtWWuCYfHMiBc9W/FOVaTA/25ls6cwUymwzqRa2nET3j01j0XQvPJgeuaX48Gz/nUVBmiqPlfZmtN5peFkZHPtYOa1rtcavtr7RvE900mhh1PubRrILJKGxmY4U/VGX3szRn7bc5jTHMsrzAChuFvvIcmRX3B+7D5258zl2fsGyhHvw3O1tSF0Y3JSP+BstyTfCH6sYPvwWYRCOIYxddyqvQirD7koN68Why9A4kZ2pLVMBxFjVksSfgAQ3cVz4c5Vbpo3fa0ciMecgMEObutOVtRKERWhh7xtxZeHPevFXBSAskEruPcKwIMshBfBlM2MVPAyPor141dzv2zrnLHqY0Nk+BzTk=
  - secure: NxnX+lJDiWQX8up9ATQOX4yhUn+KbFk9lQ3UvsCY8lAg9B0hI0XYoNCSopVy4biCNlhzYV2SgH5FrM4+MxoSflnmW2aLY+t8RQyhRWuXsh5fMesJJYBdx0Yps2dUXMtmB2BlEYRgyQv1HZO60NJkfKVphgEryz0raPniDNhSIAFqZpDQv0BZiragSFSq+cIZ1F+7xI60gJtTDQt8ENl+VSwrGs2o6PO7YIFL+1qKGj+DCTqOdWGmqQEQxk6WrsRlbvRUn88/WYT+F6zLHvqkFa4jtI5UpVyLMQJ8yAuBeZRm2/0DxYHuInyfFoPJOzn2pwzkGOJYDdqEWoXjKyFtDUsP57XsSu6/C56fqiGDHEygybnrt04pLFaO8mR2MtmsgsPboiL826U1EOmMpo0EJcg4xB4O8AFUs19g9TMDp2A7kURXQbk7WGlW5eQGAf/GeKbk9qXx4WJQAewXYoUqVDy0JteD4N6YxQMeGhOC0Hi080OiNXr+C7HKvkQAbf1m9kKqvkDeSZqeq2kzqCh0JcZ+9E72FsOnmy9NjaFfyt1lQfQjeBiRTL2cDEbYIelXbqhOdJir5lIoN3m1MUcwt49uyJG5ZTGKqtYgOABh/Wp4SF5ixML9kB1bxxnBqqvFTn2RqTY+c4BlZX5zNtoj5i3Z6XI4IS4XBF6iEYpdoUU=
